CREATE PROCEDURE [dbo].[pr_HeapCheck]

AS

SET NOCOUNT ON;

	SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_TYPE = 'BASE TABLE'
	EXCEPT
	SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS;
